# Generated by Django 4.1 on 2023-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('accessibility', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('participants', models.IntegerField()),
                ('price', models.FloatField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
